######################################################################
# Automatically generated by qmake (3.1) Fri Oct 27 18:07:55 2023
######################################################################

TEMPLATE = app
INCLUDEPATH += ./include/ 
LIBS += -L/usr/local/lib -lSDL2 

# Input
SOURCES += ./src/main.cpp ./src/mmatrix.cpp  
HEADERS += ./include/mmatrix.hpp  

# Output
TARGET = rotating-cube
OBJECTS_DIR += ./debug/
